permalink: /blog/:year/:month/:day/:title
highlighter: rouge
title: Ontola.io
description: Linked Data software developemnt
url: https://ontola.io
author:
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-release
  - jekyll-redirect-from
#i18n
languages: ["en", "nl"]
defaultLang: en
languageNames:
  en: English
  nl: Nederlands
exclude_from_localizations: ["css", "img", "js", "_posts"]
# Where it's available
production_url: "http://ontola.io"
# Direct sub-route after production URL
baseurl: ""
