permalink: /blog/:year/:month/:day/:title
highlighter: rouge
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-release
#i18n
languages: ["en", "nl"]
defaultLang: en
languageNames:
  en: English
  nl: Nederlands
exclude_from_localizations: ["css", "img", "js", "_posts"]
# Where it's available
production_url: "http://ontola.io"
# Direct sub-route after production URL
baseurl: ""
